"""Initial migration

Revision ID: 6b64d4edfdb6
Revises:
Create Date: 2025-11-26 12:56:46.120223

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b64d4edfdb6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False, comment="Foreign key to sessions table"),
        sa.Column(
            "question_id",
            sa.UUID(),
            nullable=True,
            comment="Optional foreign key to questions table",
        ),
        sa.Column(
            "agent_name",
            sa.String(length=100),
            nullable=False,
            comment="Agent that generated the answer",
        ),
        sa.Column("answer_text", sa.String(), nullable=False, comment="The answer text"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("metadata", sa.JSON(), nullable=True, comment="Additional answer metadata"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False, comment="Foreign key to sessions table"),
        sa.Column("question_text", sa.String(), nullable=False, comment="The question text"),
        sa.Column(
            "agent_name",
            sa.String(length=100),
            nullable=True,
            comment="Agent that asked/processed the question",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("metadata", sa.JSON(), nullable=True, comment="Additional question metadata"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_states",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False, comment="Foreign key to sessions table"),
        sa.Column(
            "state_key", sa.String(length=100), nullable=False, comment="State key identifier"
        ),
        sa.Column("state_value", sa.JSON(), nullable=False, comment="State value as JSON"),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            comment="State version number for tracking changes",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Session status: active, completed, failed, cancelled",
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=True,
            comment="Additional session metadata stored as JSON",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("session_states")
    op.drop_table("questions")
    op.drop_table("answers")
    # ### end Alembic commands ###
