"""SQLAlchemy ORM models for database tables."""

from datetime import datetime, timezone
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import Column, DateTime, JSON, String, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.app.db.base import Base


class Session(Base):
    """
    Session model representing a user interaction session.

    Tracks the lifecycle of a filmmaking concept generation session,
    including all questions, answers, and agent interactions.
    """

    __tablename__ = "sessions"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=text("gen_random_uuid()"),
    )

    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="active",
        comment="Session status: active, completed, failed, cancelled",
    )

    session_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata",
        JSON,
        nullable=True,
        comment="Additional session metadata stored as JSON",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=text("CURRENT_TIMESTAMP"),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __repr__(self) -> str:
        """String representation of Session."""
        return f"<Session(id={self.id}, status={self.status})>"


class Question(Base):
    """
    Question model storing user questions and agent queries.

    Tracks all questions asked during a session for conversation history
    and debugging purposes.
    """

    __tablename__ = "questions"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=text("gen_random_uuid()"),
    )

    session_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        nullable=False,
        comment="Foreign key to sessions table",
    )

    question_text: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="The question text",
    )

    agent_name: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        comment="Agent that asked/processed the question",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=text("CURRENT_TIMESTAMP"),
    )

    question_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata",
        JSON,
        nullable=True,
        comment="Additional question metadata",
    )

    def __repr__(self) -> str:
        """String representation of Question."""
        return f"<Question(id={self.id}, session_id={self.session_id})>"


class Answer(Base):
    """
    Answer model storing agent responses.

    Tracks all answers generated by agents during a session.
    """

    __tablename__ = "answers"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=text("gen_random_uuid()"),
    )

    session_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        nullable=False,
        comment="Foreign key to sessions table",
    )

    question_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        nullable=True,
        comment="Optional foreign key to questions table",
    )

    agent_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Agent that generated the answer",
    )

    answer_text: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment="The answer text",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=text("CURRENT_TIMESTAMP"),
    )

    answer_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata",
        JSON,
        nullable=True,
        comment="Additional answer metadata",
    )

    def __repr__(self) -> str:
        """String representation of Answer."""
        return f"<Answer(id={self.id}, agent={self.agent_name})>"


class SessionState(Base):
    """
    Session state snapshots for tracking agent state evolution.

    Stores periodic snapshots of session state for debugging,
    restoration, and analysis purposes.
    """

    __tablename__ = "session_states"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=text("gen_random_uuid()"),
    )

    session_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        nullable=False,
        comment="Foreign key to sessions table",
    )

    state_key: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="State key identifier",
    )

    state_value: Mapped[dict[str, Any]] = mapped_column(
        JSON,
        nullable=False,
        comment="State value as JSON",
    )

    version: Mapped[int] = mapped_column(
        nullable=False,
        default=1,
        comment="State version number for tracking changes",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=text("CURRENT_TIMESTAMP"),
    )

    def __repr__(self) -> str:
        """String representation of SessionState."""
        return f"<SessionState(id={self.id}, key={self.state_key}, v{self.version})>"

